### PR TITLE
Add options for bin, excludes, files, events, spawningArgs

### PR DESCRIPTION
**Pull request by stephaneerard**
Hello,

Thank you uvery much for this lib !

I was in need for a nodejs wrapper around inotifywait that would help me define exclusions, events to listen to, etc., so I have augmented your code to suit my needs.

### CODE REVIEW

**Comment by kerphi** [comment]
Thank you for your contribution, coudl you add few doc and maybe a small example about the new options you added ?

**Comment by stephaneerard** [comment]
Is it ok for you ? :)

**Comment by kerphi** [comment]
Great !

Thank you

**Comment by kerphi** [comment]
I just published 1.8.0

**Comment by kerphi** [comment]
I also just fixed a JSON parsing bug here:
https://github.com/Inist-CNRS/node-inotifywait/commit/dd14e9c1f01100e2e9c1b3b1e531507a2d4b09ca

**Pull request merged**
